language: perl
arch:
 - arm64
matrix:
 include:
  - dist: xenial
    perl: 5.24
    env: USE_SUDO=
  - dist: bionic
    perl: 5.26
    env: USE_SUDO=
  - dist: focal
    perl: 5.32
    env: USE_SUDO=
  - dist: focal
    env: USE_SYSTEM_PERL=1 USE_SUDO=sudo
    language: minimal

branches:
 except:
  - /appveyor/
  - /github-actions/
  - /doozer/

before_install:
  - if [ "$USE_SYSTEM_PERL" = "1" ]; then sudo apt-get update -qq; sudo apt-get install -qq cpanminus; fi

install:
  - $USE_SUDO cpanm --quiet --installdeps --notest .
  - '[ "$USE_SUDO" = "" ] || rm -f MYMETA.*'

script:
  - perl Makefile.PL && env HARNESS_TIMER=1 HARNESS_OPTIONS=j4:c make disttest
