language: perl
arch:
 - arm64
matrix:
 include:
  - dist: xenial
    perl: 5.24
  - dist: bionic
    perl: 5.26
  - dist: focal
    perl: 5.32
  - dist: focal
    language: minimal

branches:
 except:
  - /appveyor/
  - /github-actions/
  - /doozer/
